<div dir="rtl" style="text-align: right;">

<h3><b>
<p style="color: #a6f11a;">
مبانی آرایه‌ها در پای‌تورچ
</p>
</b></h3>

</div>

---

<h1 style='text-align: right;'>تنسور</h1>

<div dir="rtl" style="text-align: right;">
امروز به مفهوم تنسور در پای‌تورچ می‌پردازیم. پای‌تورچ یک پلتفرم یادگیری عمیق منبع باز که مسیری یکپارچه از نمونه سازی تحقیقاتی تا استقرار تولید را فراهم می کند. 
</div>
<div dir="rtl" style="text-align: right;">
- آرایه در نامپای معادل تنسور در پایتورچ است با این تفاوت که در پایتورچ قابلیت اجرای محاسبات در کارت گرافیکی وجود دارد.
</div>

In [ ]:
!pip install torch

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

import numpy as np

torch.manual_seed(446)
np.random.seed(446)

print(torch.__version__) 

2.5.1+cpu


In [ ]:
x = torch.tensor(3.0)
print(x.item())
print(x.shape)

3.0
torch.Size([])


In [128]:
x = torch.arange(4)
print('x = ', x)
print(x.shape)

x =  tensor([0, 1, 2, 3])
torch.Size([4])


In [129]:
A = torch.arange(20, dtype=torch.float32).reshape((5,4))
print(A)
print(A.shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
torch.Size([5, 4])


In [132]:
At = A.t()
print(At)
print(At.shape)

tensor([[ 0.,  4.,  8., 12., 16.],
        [ 1.,  5.,  9., 13., 17.],
        [ 2.,  6., 10., 14., 18.],
        [ 3.,  7., 11., 15., 19.]])
torch.Size([4, 5])


<div dir="rtl" style="text-align: right;">
همانطور که بردارها اسکالرها و ماتریس‌ها بردارها را تعمیم می‌دهند، ما می‌توانیم ساختارهای داده را حتی با محورهای بیشتری بسازیم. تنسورها روشی کلی برای بحث در مورد آرایه ها با تعداد دلخواه محور به ما می دهند. برای مثال بردارها تنسورهای مرتبه اول و ماتریس ها تنسورهای مرتبه دوم هستند.
</div>


In [125]:
X = torch.arange(24).reshape((2, 3, 4))
print('X.shape =', X.shape)
print('X =', X)

X.shape = torch.Size([2, 3, 4])
X = tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


<h3 style='text-align: right;'>آرایه نامپای چه ارتباطی با تنسور دارد؟</h3>

In [15]:
# we create tensors in a similar way to numpy nd arrays
x_numpy = np.array([0.1, 0.2, 0.3])
x_torch = torch.tensor([0.1, 0.2, 0.3])
print('x_numpy:', x_numpy )
print('x_torch:', x_torch )

x_numpy: [0.1 0.2 0.3]
x_torch: tensor([0.1000, 0.2000, 0.3000])


In [16]:
# to and from numpy, pytorch
# The tensor and ndarray share the same memory. 
print('to and from numpy and pytorch')
print('from numpy:', torch.from_numpy(x_numpy))
print('to numpy:', x_torch.numpy() )

to and from numpy and pytorch
from numpy: tensor([0.1000, 0.2000, 0.3000], dtype=torch.float64)
to numpy: [0.1 0.2 0.3]


In [19]:
# we can do basic operations like +-*/
y_numpy = np.array([3,4,5.])
y_torch = torch.tensor([3,4,5.])
print("x+y")
print(x_numpy + y_numpy, x_torch + y_torch)
# print(x_numpy + y_torch) # TypeError

x+y
[3.1 4.2 5.3] tensor([3.1000, 4.2000, 5.3000])


In [ ]:
# many functions that are in numpy are also in pytorch
print("numpy norm:", np.linalg.norm(x_numpy))
print("torch norm:", torch.norm(x_torch))

In [24]:
# to apply an operation along a dimension,
# we use the dim keyword argument instead of axis
print("mean along the 0th dimension")
x_numpy = np.array([[1,2],[3,4.]])
x_torch = torch.tensor([[1,2],[3,4.]])
print("numpy mean:", np.mean(x_numpy, axis=0))
print("torch mean:", torch.mean(x_torch, dim=0))

mean along the 0th dimension
numpy mean: [2. 3.]
torch mean: tensor([2., 3.])


In [62]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [65]:
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [64]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


<h3 style='text-align: right;'>
ایجاد تنسور هم‌شکل
</h3>

In [67]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

torch.Size([2, 2, 3])
tensor([[[-1.7007e+35,  1.7502e-42,  0.0000e+00],
         [ 2.0391e+00,  0.0000e+00,  2.0156e+00]],

        [[ 0.0000e+00,  2.0000e+00,  0.0000e+00],
         [ 2.0469e+00,  0.0000e+00,  2.0469e+00]]])


In [69]:
empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

torch.Size([2, 2, 3])
tensor([[[-1.7009e+35,  1.7502e-42,  1.4013e-45],
         [ 0.0000e+00,  1.4013e-45,  0.0000e+00]],

        [[ 1.4013e-45,  0.0000e+00,  1.4013e-45],
         [ 0.0000e+00,  1.4013e-45,  0.0000e+00]]])


In [70]:
zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [71]:
ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [68]:
rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0.5062, 0.8469, 0.2588],
         [0.2707, 0.4115, 0.6839]],

        [[0.0703, 0.5105, 0.9451],
         [0.2359, 0.1979, 0.3327]]])


<h3 style='text-align: right;'>
نوع داده تنسور
</h3>

In [72]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.3283,  0.2118, 18.4972],
        [ 9.8370,  3.8937, 16.1945]], dtype=torch.float64)
tensor([[18,  0, 18],
        [ 9,  3, 16]], dtype=torch.int32)


In [152]:
A=torch.tensor([[1,2,3],
                [4,5,6],
                [7,8,9]])
print('Slice of A:\n',A[:2,:2])
print('Second row of A:\n',A[1,:])
print('Last column of A:\n',A[:,2])

Slice of A:
 tensor([[1, 2],
        [4, 5]])
Second row of A:
 tensor([4, 5, 6])
Last column of A:
 tensor([3, 6, 9])


<h3 style='text-align: right;'>
تغییر شکل تنسور
</h3>

In [26]:
# "MNIST"
N, C, W, H = 10000, 3, 28, 28
X = torch.randn((N, C, W, H))
print(X.shape)
print(X.view(N, C, 784).shape)

torch.Size([10000, 3, 28, 28])
torch.Size([10000, 3, 784])


In [27]:
print(X.view(-1, C, 784).shape) # automatically choose the 0th dimension

torch.Size([10000, 3, 784])


In [28]:
print(torch.reshape(X, (N, C, 784)).shape)  # You can still do torch.reshape
print(torch.reshape(X, (N, -1, 784)).shape)  # Including -1 trick

torch.Size([10000, 3, 784])
torch.Size([10000, 3, 784])


if you need a copy use clone() if you need the same storage use view(). The semantics of reshape() are that it may or may not share the storage and you don't know beforehand.


In [29]:
##zeros and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [30]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [32]:
a=torch.tensor(np.arange(0,15).reshape(5,3))
print("a:\n", a)

a:
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)


In [33]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]], dtype=torch.int32)

In [107]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [109]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [110]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

torch.Size([1, 20])
tensor([[0.9232, 0.8610, 0.3343, 0.3860, 0.6696, 0.5881, 0.3480, 0.2842, 0.1122,
         0.4168, 0.9429, 0.8847, 0.0171, 0.0655, 0.0418, 0.4302, 0.8554, 0.7047,
         0.7264, 0.6029]])
torch.Size([20])
tensor([0.9232, 0.8610, 0.3343, 0.3860, 0.6696, 0.5881, 0.3480, 0.2842, 0.1122,
        0.4168, 0.9429, 0.8847, 0.0171, 0.0655, 0.0418, 0.4302, 0.8554, 0.7047,
        0.7264, 0.6029])


In [111]:
c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [113]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
d = a * c
print(c.shape)
print(d.shape)  

torch.Size([3, 1])
torch.Size([4, 3, 2])


<h3 style='text-align: right;'>
یک ماتریس تصادفی با ابعاد ۱ در ۱ در ۱ در ۱۰ ایجاد کنید.
    سپس یک ماتریس جدید یک بعدی با اندازه ۱۰ از روی این ماتریس ایجاد کنید.
</h3>

<h3 style='text-align: right;'>
تمرین: یک تنسور تصادفی چهار بعدی ایجاد و میانگین دو بعد آخر را از آن کم کنید
</h3>


In [9]:
N, C, W, H = 10000, 3, 28, 28
X = torch.randn((N, C, W, H))

X_mean1 = torch.mean(X, dim=(2, 3))
X_mean1 = X_mean1.unsqueeze(2)
X_mean1 = X_mean1.unsqueeze(3)

Y1 = X - X_mean1
print(Y1.shape)


torch.Size([10000, 3, 28, 28])


In [11]:
X_mean2 = torch.mean(X, dim=(2, 3), keepdim=True)
Y2 = X - X_mean2
print(X_mean2.shape)
print(Y2.shape)

torch.Size([10000, 3, 1, 1])
torch.Size([10000, 3, 28, 28])


<h3 style='text-align: right;'>
محاسبات تنسور
</h3>

In [12]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print("a:", a)
print("b:", b)
print("a+b:", a+b)

a: tensor([3., 4., 5.])
b: tensor([4., 5., 6.])
a+b: tensor([ 7.,  9., 11.])


In [37]:
c = torch.add(a,b)

tensor([ 7.,  9., 11.])

In [39]:
c=torch.zeros(3)
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [41]:
##### Some more operations
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
torch.add(a,b).sum()

tensor(27.)

<h3 style='text-align: right;'>
عملیات ضرب
</h3>

In [13]:
# Note: The following cell throws a run-time error. This is intentional.
x = torch.rand(2, 3)
y = torch.rand(3, 2)
print(x.shape)
print(y.shape)
x*y

torch.Size([2, 3])
torch.Size([3, 2])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [78]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)
x*y

tensor([[0.1332, 0.0023, 0.4945],
        [0.3857, 0.9883, 0.4762]])
tensor([[0.7242, 0.0776, 0.4004],
        [0.9877, 0.0352, 0.0905]])


tensor([[9.6436e-02, 1.7605e-04, 1.9800e-01],
        [3.8102e-01, 3.4814e-02, 4.3096e-02]])

In [14]:
x= torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [16]:
z = x.mul(y)
z = x*y
print(z)

tensor([12., 20., 30.])


In [ ]:
x.dot(y)


tensor(62.)

In [17]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
x.dot(y)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [19]:
###### MAtrix Multiplication
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [20]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [21]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [49]:
x@y

tensor([[55., 53.],
        [90., 92.]])

<h3 style='text-align: right;'>
تمرین:
 دو ماتزیس تصادفی یک بعدی با اندازه ۱۰ ایجاد
    و ضرب داخلی آنها را حساب کتید

torch.dot
</h3>

In [26]:
# write code cnippet here
x = torch.rand(10)
y = torch.rand(10)
print(torch.dot(x,y))
print(x.dot(y))


tensor(3.0568)
tensor(3.0568)


<h3 style='text-align: right;'>
تمرین:
یک ماتریس تصادفی
دو بعدی با ابعاد ۷ در ۷
ایجاد کنید و ان را با یک ماتریس تصادفی دیگر
با ابعاد
۱ در ۷
   (نیاز به ترانهاده کردن ماتریس دوم) ضرب کنید.
</h3>

In [29]:
# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape

# Create another random tensor
Y = torch.rand(size=(1, 7))
# Z = torch.matmul(X, Y) # will error because of shape issues
Z = torch.matmul(X, Y.T) # no error because of transpose
Z, Z.shape


(tensor([[1.5965],
         [1.6604],
         [1.5470],
         [1.3854],
         [1.3756],
         [2.0980],
         [1.5020]]),
 torch.Size([7, 1]))

<div dir="rtl" style="text-align: right;">
تنسورها معمولاً دو شکل متد دارند، یک روش که تنسور دیگر را برمی گرداند و روش دیگری که عملیات را در جای خود انجام می دهد. یعنی مقادیر موجود در حافظه برای آن تنسور بدون ایجاد تنسور جدید تغییر می کند. توابع در محل همیشه با یک زیرخط مشخص می شوند.
</div>

In [31]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
# Return a new tensor z + 1
print("x.add:\n", x.add(1))
print("x:\n", x)

x.add:
 tensor([[2., 5., 3.],
        [2., 6., 6.]])
x:
 tensor([[1., 4., 2.],
        [1., 5., 5.]])


In [32]:
print("x.add:\n", x.add_(1))
print("x:\n", x)

x.add:
 tensor([[2., 5., 3.],
        [2., 6., 6.]])
x:
 tensor([[2., 5., 3.],
        [2., 6., 6.]])


In [50]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)

<h3 style='text-align: right;'>
قاعده پخش
</h3>

In [83]:
rand = torch.rand(2, 4)
twos = torch.ones(1, 4) * 2
doubled = rand * twos

print(rand.shape)
print(twos.shape)
print(doubled.shape)

torch.Size([2, 4])
torch.Size([1, 4])
torch.Size([2, 4])


In [33]:
a =     torch.ones(4, 3, 2)
b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b.shape)

torch.Size([4, 3, 2])


In [87]:
a =     torch.ones(4, 3, 2)
c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c.shape)

torch.Size([4, 3, 2])


In [88]:
a =     torch.ones(4, 3, 2)
d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d.shape)

torch.Size([4, 3, 2])


In [34]:
# Note: The following cell throws a run-time error. This is intentional.
a =     torch.ones(4, 3, 2)
b = a * torch.rand(4, 3)    # dimensions must match last-to-first

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [35]:
# Note: The following cell throws a run-time error. This is intentional.
a =     torch.ones(4, 3, 2)
c = a * torch.rand(   2, 3) # both 3rd & 2nd dims different

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [36]:
# Note: The following cell throws a run-time error. This is intentional.
a =     torch.ones(4, 3, 2)
d = a * torch.rand((0, ))   # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (0) at non-singleton dimension 2

<h3 style='text-align: right;'>
توابع سراسری
</h3>

In [37]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

Common functions:
tensor([[ 0.0221,  0.1577, -0.6236, -0.1518],
        [-0.6776,  0.1477,  0.9644,  0.2266]])
tensor([[0.0221, 0.1577, 0.6236, 0.1518],
        [0.6776, 0.1477, 0.9644, 0.2266]])
tensor([[1., 1., -0., -0.],
        [-0., 1., 1., 1.]])
tensor([[ 0.,  0., -1., -1.],
        [-1.,  0.,  0.,  0.]])
tensor([[ 0.0221,  0.1577, -0.5000, -0.1518],
        [-0.5000,  0.1477,  0.5000,  0.2266]])


In [93]:
# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)


Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [38]:
# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))


Bitwise XOR:
tensor([3, 2, 1])


In [42]:
# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
f = torch.tensor([[1., 2.]])
print(e)
print(f)
print(torch.eq(d, f)) # returns a tensor of type bool



Broadcasted, element-wise equality comparison:
tensor([[1., 1.]])
tensor([[1., 2.]])
tensor([[ True,  True],
        [False, False]])


In [ ]:
# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements



Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [43]:
torch.max(d).item()


4.0

In [44]:
torch.max(d)

tensor(4.)

<div dir="rtl" style="text-align: right;"> 
    تمرین:
دو تنسور تصادفی شکل 2 در 3 ایجاد کنید و در صورت وجود هر دو را به کارت گرافیکی بفرستیدهنگام ایجاد تنسورها،

 torch.manual_seed(1234)

را تنظیم کنید خروجی باید چیزی شبیه به این باشد:
</div>

Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


In [45]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B


Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

<div dir="rtl" style="text-align: right;"> 
ضرب ماتریسی ماتریس اول در ترانهاده ماتریس دوم بالا انجام دهید:
</div>


In [46]:
# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

<div dir="rtl" style="text-align: right;"> 
مقدار کمینه و بیشبنه ماتریس حاصلضرب را پیدا کنید
</div>


In [ ]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min


(tensor(0.5617), tensor(0.3647))

In [52]:
d = torch.tensor([[1., 5.], [3., 4.]])
torch.argmax(d)

tensor(1)

<div dir="rtl" style="text-align: right;"> 
اندیس مقادیر کمینه و بیشبنه ماتریس حاصلضرب را پیدا کنید
</div>


In [53]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min



(tensor(3), tensor(0))

In [54]:
# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)


print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition


Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.7749, 0.8208],
        [0.2793, 0.6817]])
tensor([[2.3246, 2.4624],
        [0.8378, 2.0451]])
torch.return_types.svd(
U=tensor([[-0.8445, -0.5356],
        [-0.5356,  0.8445]]),
S=tensor([3.9870, 0.6749]),
V=tensor([[-0.6049, -0.7963],
        [-0.7963,  0.6049]]))


C:\Users\user\AppData\Local\Temp\ipykernel_14564\272325983.py:8: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Cross.cpp:66.)
  print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)


<h3 style='text-align: right;'>
کپی کردن تنسور
</h3>

In [71]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b) 

assert b is a      # different objects in memory...



tensor([[  1., 561.],
        [  1.,   1.]])


In [56]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)  

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


<h3 style='text-align: right;'>
انتقال محاسبات به کارت گرافیکی
</h3>

In [57]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


In [58]:
if torch.cuda.is_available():
    rand = torch.rand(2, 2, device='cuda')
    print(rand)
else:
    rand = torch.rand(2, 2, device='cpu')
    print(rand)


tensor([[0.2837, 0.6567],
        [0.2388, 0.7313]])


In [59]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)


Device: cpu
tensor([[0.6012, 0.3043],
        [0.2548, 0.6294]])


In [60]:
y = torch.rand(2, 2)
y = y.to(my_device)

In [61]:
y.device

device(type='cpu')

<h3 style='text-align: right;'>
جبر خطی در پای‌تورچ
</h3>

In [62]:
import torch
from torch import linalg

In [63]:
# define a matrix with Tensor
A=torch.Tensor([[1,2],[3,4]])
B=torch.Tensor([[3,1],[2,5]])
print('A:',A.tolist())
print('B:',B.tolist())

A: [[1.0, 2.0], [3.0, 4.0]]
B: [[3.0, 1.0], [2.0, 5.0]]


In [64]:
print('Determinant of A:',linalg.det(A).item())
print('Inverse of A:\n',linalg.inv(A))
print('A* A^-1:\n',(A@linalg.inv(A)))

Determinant of A: -2.0
Inverse of A:
 tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])
A* A^-1:
 tensor([[1., 0.],
        [0., 1.]])


In [65]:
# a square matrix and its eigenvalues and eigenvectors
A=torch.Tensor([[1,2],[0,3]])
print('The square matrix:',A.tolist())

The square matrix: [[1.0, 2.0], [0.0, 3.0]]


In [66]:
# getting eigenvalues and eigenvectors
eigvals,eigvecs=linalg.eig(A)
print('Eigenvalues:',eigvals.tolist())
print('Eigenvectors:\n',eigvecs.tolist())

Eigenvalues: [(1+0j), (3+0j)]
Eigenvectors:
 [[(1+0j), (0.7071067690849304+0j)], [0j, (0.7071067690849304+0j)]]


In [67]:
print('Sum of eigenvalues:',eigvals.sum().item())
print('Sum of digonal elements:',A.diag().sum().item())

Sum of eigenvalues: (4+0j)
Sum of digonal elements: 4.0


In [68]:
print('Product of eigenvalues:',eigvals.prod().item())
print('Determinant of matrix:',A.det().item())

Product of eigenvalues: (3+0j)
Determinant of matrix: 3.0


In [69]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

<div dir="rtl" style="text-align: right;"> 
    تمرین:
نشان بدهید ترانهاده ترانهاده یک ماتریس برابر با خود آن ماتریس است
</div>


<div dir="rtl" style="text-align: right;"> 
    تمرین:
برای دو ماتریس دلخواه نشان بدهید که حاصل جمع ترانهاده دو ماتریس با ترانهاده حاصل جمع دو ماتریس برابر است
</div>


<div dir="rtl" style="text-align: right;"> 
    تمرین:
یک ماتریس متقارن دلخواه ایجاد کنید
</div>
